# Generated by Django 5.0.4 on 2024-04-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('category_image', models.ImageField(upload_to='images/', verbose_name='Картинка категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255, verbose_name='Название производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_in_stock', models.BooleanField(default=False, verbose_name='Товар в наличии')),
                ('product_description', models.TextField(verbose_name='Описание товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена товара')),
                ('product_image', models.ImageField(upload_to='images/', verbose_name='Картинка товара')),
                ('categories', models.ManyToManyField(to='web_app.category', verbose_name='Категории товара')),
                ('product_manufactuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.manufacturer', verbose_name='Производитель товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
                'db_table': 'product_images',
            },
        ),
    ]
