# Generated by Django 5.0.4 on 2024-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='web_app.category', verbose_name='Категории товара'),
        ),
    ]
