# Generated by Django 5.0.4 on 2024-04-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_manufactuer',
            new_name='product_manufacturer',
        ),
    ]
